dualidade/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
 path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
    path('novo-perfil/',views.add_user_profile, name='add_user_profile'),
    path('meu-perfil/',views.list_user_profile, name='list_user_profile'),
    path('alterar-perfil/<username>/',views.change_user_profile, name='change_user_profile'),
]

dualidade/apps/categories/urls.py
from django.urls import path
from . import views

app_name = 'categories'

urlpatterns = [
    path('', views.list_categories, name='list_categories'),
    path('adicionar/', views.add_category, name='add_category'),
    path('editar/<int:id_category>/', views.edit_category, name='edit_category'),
    path('excluir/<int:id_category>/', views.delete_category, name='delete_category'),
]

dualidade/apps/demands/urls.py
from django.urls import path
from . import views

app_name = 'demands'

urlpatterns = [
    path('', views.list_demands, name='list_demands'),
    path('adicionar/<int:id_client>/', views.add_demands, name='add_demands'),
    path('excluir/<int:id_demands>/', views.delete_demands, name='delete_demands'),
    path('excluir-item/<int:id_demands_item>/', views.delete_demands_item, name='delete_demands_item'),
    path('adicionar-item/<int:id_demands>/', views.add_demands_item, name='add_demands_item'),
    path('editar-status/<int:id_demands>/', views.edit_demands_status, name='edit_demands_status'),
]

dualidade/dualidade/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('pedidos/', include('demands.urls', namespace='demands')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dualidade/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}Dualidade App{% endblock title %}</title>
</head>
<body>

    <!-- INICIO: Bloco do Bootstrap a ser incluido -->
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="/">Dualidade App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'demands:list_demands' %}">Pedidos</a>
                        <a class="dropdown-item" href="{% url 'categories:list_categories' %}">Categorias</a>
                        
                    </div>
                </li>
            </ul>
            <form action="#" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item"> 
                        <img src="{% static 'img/user.png' %}" class="rounded-circle" width="40" height="40" >
                    
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown05">
                            <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                            <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                            <a class="dropdown-item" href="{% url 'accounts:list_user_profile' %}">Perfil</a>                    <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                        </div>
                </li>
            </ul>
        </div>
        {% endif %}
    </nav>
    <!-- FIM: Bloco do Bootstrap a ser incluido -->
    {% block body %}
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="assets/vendor/purecounter/purecounter.js"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/glightbox.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>
</html>