dualidade/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
 path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
    path('novo-perfil/',views.add_user_profile, name='add_user_profile'),
    path('meu-perfil/',views.list_user_profile, name='list_user_profile'),
    path('alterar-perfil/<username>/',views.change_user_profile, name='change_user_profile'),
]

dualidade/dualidade/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('pedidos/', include('demands.urls', namespace='demands')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dualidade/apps/accounts/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    photo = models.ImageField('Foto', upload_to='photos')
    cell_phone = models.CharField('Celular', max_length=16)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    class Meta:
        verbose_name = 'Perfil do usuario'
        verbose_name_plural = 'Perfis dos usuarios'

    def __str__(self):
        return self.user.username

dualidade/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password' , 'email']

class UserChangeInformationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']

dualidade/apps/accounts/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from .forms import UserForm, UserChangeInformationForm
from .models import UserProfile
# Create your views here.

def add_user(request):
    template_name = 'accounts/add_user.html'
    context = {}
    if request.method =='POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
    form = UserForm()
    context['form'] = form
    return render(request, template_name, context)

def user_login(request):
    template_name = 'accounts/user_login.html'
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get('next', '/'))
    return render(request, template_name, {})

@login_required(login_url='/contas/login/')
def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')

@login_required(login_url='/contas/login/')
def user_change_password(request):
    template_name = 'accounts/user_change_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
    form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def add_user_profile(request):
    template_name = 'accounts/add_user_profile.html'
    context = {}
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
    form = UserProfileForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_user_profile(request):
    template_name = 'accounts/list_user_profile.html'
    context = {}
    profile = None
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        pass
    context['profile'] = profile
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def change_user_profile(request, username):
    template_name = 'accounts/add_user_profile.html'
    context = {}
    profile = UserProfile.objects.get(user__username=username) # comaparando strings usnado 2 anderline
    if request.method == 'POST':    
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
    form = UserProfileForm(instance=profile)
    context['form'] = form
    context['profile'] = profile
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def user_change_information(request, username):
    template_name = 'accounts/change_user_information.html'
    context = {}
    user = User.objects.get(username=username)
    if request.method == 'POST':
        form = UserChangeInformationForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
    form = UserChangeInformationForm(instance=user)
    context['form'] = form
    return render(request, template_name, context)

dualidade/templates/accounts/add_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Novo usuario - {{ block.super}}
{% endblock title %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
            <h1>Novo usuario</h1>
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.first_name.id_for_label }}">Nome</label>
                        {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                        {{ form.last_name|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}">Nome de usuario</label>
                        {{ form.username|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">E-mail</label>
                        {{ form.email|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.password.id_for_label }}">Senha</label>
                        {{ form.password|add_class:"form-control"|attr:"type:password" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

dualidade/templates/accounts/add_user_profile.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}
    Alterar Perfil - {{ block.super }}
{% endblock title %}



{% block body %}
    
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Alterar Perfil</h1>
            {% if profile %}
                <img src="{{ profile.photo.url }}" class="align-self-start mr-3 rounded-circle" width="100" height="100">
            {% endif %}
            <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.photo.id_for_label }}">Foto de Perfil</label>
                    {{ form.photo|add_class:"form-control-file" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.cell_phone.id_for_label }}">Celular</label>
                    {{ form.cell_phone|add_class:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>
</div>


{% endblock body %}
    
    

dualidade/templates/accounts/change_user_information.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Novo usuario - {{ block.super}}
{% endblock title %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
            <h1>Alterar usuario</h1>
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.first_name.id_for_label }}">Primerio nome</label>
                        {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                        {{ form.last_name|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">E-mail</label>
                        {{ form.email|add_class:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

dualidade/templates/accounts/list_user_profile.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}


{% block blockname %}
    Meu Perfil - {{ block.super }}
{% endblock blockname %}


{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <h1>Meu Perfil</h1>
            {% if profile %}
                <div class="media">
                    <img src="{{ profile.photo.url }}" class="align-self-start mr-3 rounded-circle" width="100" height="100">
                    <div class="media-body">
                        <h5 class="mt-0">{{ profile.user.get_full_name }}</h5>
                        <p>Celular: {{ profile.cell_phone }}</p>
                        <p>Celular: {{ profile.user.email }}</p>
                    </div>
                </div>
                <a href="{% url 'accounts:change_user_profile' user.username %}" class="btn btn-primary">Alterar Perfil</a>
            {% else %}
                <h2>Voce ainda nao criou um perfil</h2>
                <a href="{% url 'accounts:add_user_profile' %}" class="btn btn-primary">Criar Perfil</a>
            {% endif %} 
                
            </div>
        </div>
    </div>
{% endblock body %}

dualidade/templates/accounts/user_change_information.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Novo usuario - {{ block.super}}
{% endblock title %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
            <h1>Alterar usuario</h1>
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.first_name.id_for_label }}">Primerio nome</label>
                        {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                        {{ form.last_name|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">E-mail</label>
                        {{ form.email|add_class:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

dualidade/templates/accounts/user_change_password.html
{% extends 'base.html' %}

{% load widget_tweaks %}


{% block title %}
    Trocar senha - {{ block.super}}
{% endblock title %}
    

{% block body %}
    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Alterar Senha</h1>
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.old_password.id_for_label }}">Senha anterior</label>
                        {{ form.old_password|add_class:"form-control"|attr:"type:password" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.new_password1.id_for_label }}">Nova senha</label>
                        {{ form.new_password1|add_class:"form-control"|attr:"type:password" }}
                    <div class="form-group">
                        <label for="{{ form.new_password2.id_for_label }}">Confirmar nova senha</label>
                        {{ form.new_password2|add_class:"form-control"|attr:"type:password" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </form>
            </div>
        </div>
    </div>
    
{% endblock body %}

dualidade/templates/accounts/user_login.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dualdade login</title>
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
  <link rel="stylesheet" href="{% static 'css/signin.css' %}" >
</head>
<body class="text-center">

  <form class="form-signin" action="" method="POST">
  {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Identifique-se</h1>
    <label for="username" class="sr-only">Usuario</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="Nome de usuario" required autofocus>
    <label for="password" class="sr-only">Senha</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Digite sua senha" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
    <br />
    <a href="{% url 'accounts:add_user' %}">Criar uma conta</a>
  </form>

  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>